### ISSUE TITLE
NoneType object when try to unassign the stock (stock_assign_manual)

### ISSUE THREAD

**Issue by JonatanLGk** [NaN-tic/trytond-stock_move_description#1]
## The problem

Problem with [Stock Assign Manual Module 6.0](https://github.com/tryton/stock_assign_manual/tree/6.0)

When I try via Wizard on Customer Shipment unassign the stock, the wizard raise an error.

```python
Traceback (most recent call last):
  File "/trytond/wsgi.py", line 117, in dispatch_request
    return endpoint(request, **request.view_args)
  File "/trytond/protocols/dispatcher.py", line 46, in rpc
    return methods.get(request.rpc_method, _dispatch)(
  File "/trytond/wsgi.py", line 84, in auth_required
    return wrapped(*args, **kwargs)
  File "/trytond/protocols/wrappers.py", line 159, in wrapper
    return func(request, pool, *args, **kwargs)
  File "/trytond/protocols/dispatcher.py", line 180, in _dispatch
    result = rpc.result(meth(*c_args, **c_kwargs))
  File "/trytond/wizard/wizard.py", line 314, in execute
    return wizard._execute(state_name)
  File "/trytond/wizard/wizard.py", line 345, in _execute
    result = self._execute(transition())
  File "/trytond/modules/stock_assign_manual/stock.py", line 357, in transition_unassign
    self.record.unassign(moves, quantities)
  File "/trytond/model/descriptors.py", line 31, in newfunc
    return self.func(owner, [instance], *args, **kwargs)
  File "/trytond/modules/stock_assign_manual/stock.py", line 47, in unassign
    cls.wait(shipments, to_unassign)
  File "/trytond/model/modelview.py", line 775, in wrapper
    return func(cls, records, *args, **kwargs)
  File "/trytond/model/workflow.py", line 37, in wrapper
    result = func(cls, filtered, *args, **kwargs)
  File "/trytond/modules/stock/shipment.py", line 1265, in wait
    inventory_move = shipment._get_inventory_move(move)
  File "/trytond/modules/stock_move_description/stock.py", line 44, in _get_inventory_move
    new_move.description = move.description
AttributeError: 'NoneType' object has no attribute 'description'

Fault: 'NoneType' object has no attribute 'description'
```

## Environment

* Trytond server version: `6.0` 
* Empty environment with db filled by `tryton-tools/tryton-demo.py`
* Only `stock_assign manual` and `stock_move_description` installed modules

[//]: # ()
* Note: We tried too into our production/development environment and raise same error.

## Possible solution

```
diff --git a/stock.py b/stock.py
index 3597b4f..825ec95 100644
--- a/stock.py
+++ b/stock.py
@@ -41,7 +41,8 @@ class ShipmentOut(metaclass=PoolMeta):
     def _get_inventory_move(self, move):
         # copy description from outgoing to inventory
         new_move = super(ShipmentOut, self)._get_inventory_move(move)
-        new_move.description = move.description
+        if new_move:
+            new_move.description = move.description
         return new_move
```

**Comment by raimonesteve** [comment]
It's ok. Do PR 'stock.shipment.out' and 'stock.shipment.in' in case new_move is not None, not set "description".
